name = "ControlPlots"
uuid = "23c2ee80-7a9e-4350-b264-8e670f12517c"
authors = ["Uwe Fechner <u.fechner-1@tudelft.nl> and contributors"]
version = "0.0.3"

[deps]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"

[compat]
julia = "1"
PyPlot = "~2.11"
JLD2 = "~0.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
