name = "ControlPlots"
uuid = "23c2ee80-7a9e-4350-b264-8e670f12517c"
authors = ["Uwe Fechner <u.fechner-1@tudelft.nl> and contributors"]
version = "0.2.6"

[deps]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"

[weakdeps]
ControlSystemsBase = "aaaaaaaa-a6ca-5380-bf3e-84a91bcd477e"

[extensions]
ControlPlotsExt = "ControlSystemsBase"

[compat]
ControlSystemsBase = "1"
JLD2 = "~0.3, ~0.4, ~0.5"
LaTeXStrings = "1"
Pkg = "1"
PyPlot = "~2.11"
StaticArraysCore = "1.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ControlSystemsBase"]
